import { generateSlug } from "@/lib/utils"

export type Project = {
  id: number
  title: string
  description: string
  category: string
  projectType: string
  technologies: string[]
  githubUrl?: string
  demoUrl: string
  slug: string
  color?: string
  challenge?: string
  solution?: string
  image?: string
}

export const projects: Project[] = [
  {
    id: 1,
    title: "Financial Dashboard – Supabase Integration",
    description: "Responsive dashboard with Supabase (auth, realtime, storage) built using Next.js, TailwindCSS, and ShadCN.",
    category: "Cross-platform",
    projectType: "Personal Project",
    technologies: ["React 19", "Next.js 15", "Supabase", "TailwindCSS", "ShadCN", "TypeScript"],
    githubUrl: "https://github.com/sabasiddique1/financial-dashboard-supabase",
    demoUrl: "https://financial-dashboard-supabase-r2su.vercel.app/",
    slug: generateSlug("Financial Dashboard – Supabase Integration"),
    color: "#00F5FF",
    image: "/placeholder.jpg",
    challenge: "Building a comprehensive financial dashboard that requires real-time data synchronization, secure authentication, and efficient data storage while maintaining a responsive and intuitive user interface.",
    solution: "Implemented Supabase for backend services including authentication, real-time subscriptions, and storage. Used Next.js 15 with React Server Components for optimal performance, and ShadCN UI components for a consistent, accessible design system.",
  },
  {
    id: 2,
    title: "Vaultix - Cloud Storage App",
    description: "A cloud storage app for easy file management with secure sharing options and high scalability.",
    category: "Cross-platform",
    projectType: "Personal Project",
    technologies: ["React 19", "Next.js 15", "Appwrite", "TailwindCSS", "ShadCN", "TypeScript"],
    githubUrl: "https://github.com/sabasiddique1/Vaultix.git",
    demoUrl: "https://vaultix-5ndl.vercel.app/sign-in",
    slug: generateSlug("Vaultix - Cloud Storage App"),
    color: "#B026FF",
    image: "/placeholder.jpg",
    challenge: "Creating a scalable cloud storage solution with secure file sharing, user management, and efficient file handling capabilities.",
    solution: "Leveraged Appwrite as a backend-as-a-service platform for authentication, database, and storage. Built with Next.js 15 and TypeScript for type safety, implementing efficient file upload/download mechanisms with progress tracking.",
  },
  {
    id: 3,
    title: "Task Management App",
    description: "A simple yet effective task management tool to help users track and organize their daily tasks.",
    category: "Cross-platform",
    projectType: "Collaborative Project",
    technologies: ["Vercel", "Next.js", "TailwindCSS", "ShadCN"],
    githubUrl: "https://github.com/sabasiddique1/Task_Management_App_MERN.git",
    demoUrl: "https://v0-mern-task-management-rho.vercel.app/login",
    slug: generateSlug("Task Management App"),
    color: "#00F5FF",
    image: "/placeholder.jpg",
    challenge: "Building a collaborative task management application that supports real-time updates, user collaboration, and intuitive task organization.",
    solution: "Developed a full-stack MERN application with real-time synchronization, drag-and-drop task organization, and collaborative features. Used modern React patterns for state management and optimized rendering.",
  },
  {
    id: 4,
    title: "Rapid API Hub Clone",
    description: "RapidAPI Hub clone with API browsing and testing flows, built with Next.js, TypeScript, and TailwindCSS.",
    category: "Cross-platform",
    projectType: "Collaborative Project",
    technologies: ["Vercel", "Next.js", "TailwindCSS", "ShadCN", "Axios"],
    githubUrl: "https://github.com/sabasiddique1/rapid-api-hub",
    demoUrl: "https://rapid-api-hub.vercel.app/",
    slug: generateSlug("Rapid API Hub Clone"),
    color: "#B026FF",
    image: "/placeholder.jpg",
    challenge: "Recreating the RapidAPI Hub experience with API discovery, testing capabilities, and a seamless browsing interface.",
    solution: "Built a comprehensive API hub with search functionality, API documentation rendering, and integrated testing tools. Implemented efficient API calls with Axios and created reusable components for consistent UI.",
  },
  {
    id: 5,
    title: "Web Scraping App",
    description: "A web scraping app that extracts valuable data from websites for analysis and research.",
    category: "Cross-platform",
    projectType: "Collaborative Project",
    technologies: ["Vercel", "Next.js", "TailwindCSS", "ShadCN"],
    githubUrl: "https://github.com/Aniketsy/Web_Scrapper_App.git",
    demoUrl: "https://web-scrapper-app-kappa.vercel.app/",
    slug: generateSlug("Web Scraping App"),
    color: "#00F5FF",
    image: "/placeholder.jpg",
    challenge: "Creating a user-friendly web scraping tool that can extract structured data from various websites while handling different page structures and formats.",
    solution: "Developed a flexible scraping engine that adapts to different website structures. Built an intuitive interface for configuring scraping parameters and visualizing extracted data in real-time.",
  },
  {
    id: 6,
    title: "NFT Detail Page – Web3 UI",
    description: "Built NFT detail UI with Next.js & Tailwind, featuring timer and metadata display.",
    category: "Cross-Platform",
    projectType: "Personal Project",
    technologies: ["Next.js", "TailwindCSS", "React lucide"],
    githubUrl: "https://github.com/sabasiddique1/nft-detail-screen.git",
    demoUrl: "https://nft-detail-screen.vercel.app/",
    slug: generateSlug("NFT Detail Page – Web3 UI"),
    color: "#B026FF",
    image: "/placeholder.jpg",
    challenge: "Designing an engaging NFT detail page that showcases metadata, countdown timers, and Web3 interactions in a modern, visually appealing interface.",
    solution: "Created a sleek NFT detail page with real-time countdown timers, animated metadata displays, and smooth transitions. Used TailwindCSS for responsive design and React Lucide for consistent iconography.",
  },
  {
    id: 7,
    title: "Portfolio - Project Showcase App",
    description: "A project showcase website highlighting experience, skills, work history.",
    category: "Cross-platform",
    projectType: "Personal Project",
    technologies: ["React 19", "Next.js 15", "TailwindCSS", "ShadCN", "TypeScript", "Framer Motion"],
    githubUrl: "https://github.com/sabasiddique1/Portfolio-website.git",
    demoUrl: "https://portfolio-website-phi-ten-96.vercel.app/",
    slug: generateSlug("Portfolio - Project Showcase App"),
    color: "#00F5FF",
    image: "/placeholder.jpg",
    challenge: "Building a modern, animated portfolio website that effectively showcases projects, skills, and experience while maintaining excellent performance and SEO.",
    solution: "Developed a fully responsive portfolio with Framer Motion animations, dark mode support, and optimized performance. Implemented smooth page transitions and interactive elements to create an engaging user experience.",
  },
  {
    id: 8,
    title: "Pokedex - Pokemon App",
    description: "A fun and interactive Pokedex app that allows users to explore and search through a collection of Pokemon.",
    category: "Web App",
    projectType: "Personal Project",
    technologies: ["Node.js", "React", "CSS"],
    githubUrl: "https://github.com/sabasiddique1/Pokedex_App.git",
    demoUrl: "https://pokedex-app-sigma-silk.vercel.app/pokemon",
    slug: generateSlug("Pokedex - Pokemon App"),
    color: "#B026FF",
    image: "/placeholder.jpg",
    challenge: "Creating an interactive Pokemon encyclopedia with search, filtering, and detailed Pokemon information display.",
    solution: "Built a responsive Pokedex application with real-time search, Pokemon card displays, and detailed information pages. Integrated with Pokemon API for comprehensive data.",
  },
  {
    id: 9,
    title: "Miniature App",
    description: "A collection of small, functional web apps built with JavaScript to demonstrate core logic and UI concepts in a lightweight format.",
    category: "Web App",
    projectType: "Personal Project",
    technologies: ["JavaScript", "HTML", "CSS"],
    githubUrl: "https://github.com/sabasiddique1/miniatureapps.git",
    demoUrl: "https://miniatureapps.vercel.app/",
    slug: generateSlug("Miniature App"),
    color: "#00F5FF",
    image: "/placeholder.jpg",
    challenge: "Creating a collection of lightweight, functional mini-applications that demonstrate various JavaScript concepts and UI patterns.",
    solution: "Developed multiple small applications showcasing different JavaScript patterns, DOM manipulation, and CSS techniques. Each app is self-contained and demonstrates specific programming concepts.",
  },
  {
    id: 10,
    title: "Event_Bazaar - Event Management App",
    description: "An event management app that allows users to organize, manage, and attend events easily.",
    category: "Cross-platform",
    projectType: "Personal Project",
    technologies: ["Node.js", "Next.js", "TypeScript", "TailwindCSS", "Stripe", "Zod", "React Hook Form", "ShadCN", "uploadthing"],
    githubUrl: "https://github.com/sabasiddique1/Event_Bazaar.git",
    demoUrl: "https://event-bazaar-3fht.vercel.app/",
    slug: generateSlug("Event_Bazaar - Event Management App"),
    color: "#B026FF",
    image: "/placeholder.jpg",
    challenge: "Building a comprehensive event management platform with payment integration, file uploads, form validation, and user management.",
    solution: "Created a full-featured event management system with Stripe payment integration, secure file uploads via UploadThing, form validation with Zod and React Hook Form, and a modern UI with ShadCN components.",
  },
  {
    id: 11,
    title: "VPC+",
    description: "Cloud-based SaaS for end-to-end multi-cloud migrations, disaster recovery, cost optimization, and compliance tracking. Fixed key bugs and improved overall stability.",
    category: "Web App",
    projectType: "Company Project",
    technologies: ["React.js", "Node.js", "PostgreSQL", "TailwindCSS"],
    demoUrl: "https://www.wanclouds.net/vpc+",
    slug: generateSlug("VPC+"),
    color: "#00F5FF",
    image: "/placeholder.jpg",
    challenge: "Working on a complex cloud infrastructure management platform, fixing critical bugs, and improving system stability and performance.",
    solution: "Identified and resolved critical bugs in the multi-cloud migration workflows. Optimized database queries, improved error handling, and enhanced the overall user experience of the platform.",
  },
  {
    id: 12,
    title: "SECMON AI",
    description: "AI-focused security platform offering real-time observability, access control, and automated vulnerability management for AI and LLM deployments.",
    category: "Web App",
    projectType: "Company Project",
    technologies: ["React.js", "Next.js", "TailwindCSS", "Python", "ML Integration"],
    demoUrl: "#",
    slug: generateSlug("SECMON AI"),
    color: "#B026FF",
    image: "/placeholder.jpg",
    challenge: "Building an AI security platform that monitors and protects AI/LLM deployments with real-time threat detection and automated responses.",
    solution: "Developed a comprehensive security monitoring platform with real-time observability, ML-powered threat detection, and automated vulnerability management. Integrated Python ML models with React frontend for seamless user experience.",
  },
  {
    id: 13,
    title: "EasyLlama",
    description: "Compliance training platform interfaces built with a modern React stack.",
    category: "Company Project",
    projectType: "Company Project",
    technologies: ["Next.js", "TailwindCSS", "ShadCN"],
    demoUrl: "#",
    slug: generateSlug("EasyLlama"),
    color: "#00F5FF",
    image: "/placeholder.jpg",
    challenge: "Creating intuitive interfaces for compliance training that engage users while ensuring comprehensive learning outcomes.",
    solution: "Built modern, accessible training interfaces using Next.js and ShadCN components. Focused on creating engaging learning experiences with progress tracking and interactive content.",
  },
  {
    id: 14,
    title: "SendScale",
    description: "Messaging and delivery platform with robust monitoring and UI tooling.",
    category: "Company Project",
    projectType: "Company Project",
    technologies: ["Next.js", "NestJS", "Ant Design", "TailwindCSS", "Sentry"],
    demoUrl: "#",
    slug: generateSlug("SendScale"),
    color: "#B026FF",
    image: "/placeholder.jpg",
    challenge: "Developing a scalable messaging platform with comprehensive monitoring, error tracking, and intuitive UI for managing delivery operations.",
    solution: "Built a full-stack messaging platform with NestJS backend and Next.js frontend. Integrated Sentry for error monitoring, implemented real-time delivery tracking, and created intuitive dashboards for operations management.",
  },
  {
    id: 15,
    title: "WhisperAI",
    description: "AI-powered platform with advanced features for AI/LLM interactions and management. Improved dashboard performance and resolved critical bugs.",
    category: "Web App",
    projectType: "Company Project",
    technologies: ["React.js", "Next.js", "TailwindCSS", "MUI", "AI Integration", "Node.js"],
    demoUrl: "#",
    slug: generateSlug("WhisperAI"),
    color: "#00F5FF",
    image: "/placeholder.jpg",
    challenge: "Building an AI-powered platform with complex AI/LLM integration, ensuring high performance and reliability while maintaining an intuitive user interface.",
    solution: "Developed advanced AI features with optimized dashboard performance, resolved 100+ bugs, and improved UX with reusable UI components. Maintained <2% API failure rate and supported scalable deployments.",
  },
  {
    id: 16,
    title: "SecMon",
    description: "Security monitoring platform with real-time threat detection and comprehensive security management features.",
    category: "Web App",
    projectType: "Company Project",
    technologies: ["React.js", "Next.js", "TailwindCSS", "MUI", "Security", "Node.js"],
    demoUrl: "#",
    slug: generateSlug("SecMon"),
    color: "#B026FF",
    image: "/placeholder.jpg",
    challenge: "Creating a comprehensive security monitoring platform with real-time threat detection, dashboard performance optimization, and reliable security features.",
    solution: "Developed security monitoring features with improved dashboard speed by 28%, built reusable UI components with MUI/Tailwind, and maintained high reliability with <2% API failure rate.",
  },
]

