import { generateSlug } from "@/lib/utils"

export type Project = {
  id: number
  title: string
  description: string
  category: string
  projectType: string
  technologies: string[]
  githubUrl?: string
  demoUrl: string
  slug: string
  color?: string
  challenge?: string
  solution?: string
  image?: string
  images?: string[] // Array of images for carousel
  featured?: boolean
}

export const projects: Project[] = [
  {
    id: 1,
    title: "Financial Dashboard – Supabase Integration",
    description: "Responsive dashboard with Supabase integration for authentication, realtime updates, and storage. Built using Next.js, TailwindCSS, and ShadCN components.",
    category: "Cross-platform",
    projectType: "Personal Project",
    technologies: ["React 19", "Next.js 15", "Supabase", "TailwindCSS", "ShadCN", "TypeScript"],
    githubUrl: "https://github.com/sabasiddique1/financial-dashboard-supabase",
    demoUrl: "https://financial-dashboard-supabase-r2su.vercel.app/",
    slug: generateSlug("Financial Dashboard – Supabase Integration"),
    color: "#00F5FF",
    image: "/financial.png",
    images: [
      "/financial.png",
      "/financial2.png",
    ],
    featured: true,
  },
  {
    id: 2,
    title: "Vaultix - Cloud Storage App",
    description: "A cloud storage app for easy file management with secure sharing options. Built with high scalability and modern web technologies.",
    category: "Cross-platform",
    projectType: "Personal Project",
    technologies: ["React 19", "Next.js 15", "Appwrite", "TailwindCSS", "ShadCN", "TypeScript"],
    githubUrl: "https://github.com/sabasiddique1/Vaultix.git",
    demoUrl: "https://vaultix-5ndl.vercel.app/sign-in",
    slug: generateSlug("Vaultix - Cloud Storage App"),
    color: "#B026FF",
    image: "/vault.png",
    images: [
      "/vault.png",
      "/vault3.png",
    ],
    featured: true,
  },
  {
    id: 3,
    title: "Task Management App",
    description: "A simple yet effective task management tool to help users track and organize their daily tasks. Features real-time collaboration and intuitive task organization.",
    category: "Cross-platform",
    projectType: "Collaborative Project",
    technologies: ["Vercel", "Next.js", "TailwindCSS", "ShadCN"],
    githubUrl: "https://github.com/sabasiddique1/Task_Management_App_MERN.git",
    demoUrl: "https://v0-mern-task-management-rho.vercel.app/login",
    slug: generateSlug("Task Management App"),
    color: "#00F5FF",
    image: "/task.png",
    images: [
      "/task.png",
      "/task2.png",
    ],
    featured: true,
  },
  {
    id: 4,
    title: "Rapid API Hub Clone",
    description: "RapidAPI Hub clone with API browsing and testing flows. Built with Next.js, TypeScript, and TailwindCSS for a seamless developer experience.",
    category: "Cross-platform",
    projectType: "Collaborative Project",
    technologies: ["Vercel", "Next.js", "TailwindCSS", "ShadCN", "Axios"],
    githubUrl: "https://github.com/sabasiddique1/rapid-api-hub",
    demoUrl: "https://rapid-api-hub.vercel.app/",
    slug: generateSlug("Rapid API Hub Clone"),
    color: "#B026FF",
    image: "/rapid.png",
    images: [
      "/rapid.png",
      "/rapid2.png",
    ],
    featured: true,
  },
  {
    id: 5,
    title: "Web Scraping App",
    description: "A web scraping app that extracts valuable data from websites for analysis and research. Features intuitive configuration and real-time data visualization.",
    category: "Cross-platform",
    projectType: "Collaborative Project",
    technologies: ["Vercel", "Next.js", "TailwindCSS", "ShadCN"],
    githubUrl: "https://github.com/Aniketsy/Web_Scrapper_App.git",
    demoUrl: "https://web-scrapper-app-kappa.vercel.app/",
    slug: generateSlug("Web Scraping App"),
    color: "#00F5FF",
    image: "/scrape.png",
    images: [
      "/scrape.png",
      "/scrape2.png",
    ],
  },
  {
    id: 6,
    title: "NFT Detail Page – Web3 UI",
    description: "Built NFT detail UI with Next.js and TailwindCSS. Features countdown timer and comprehensive metadata display for Web3 interactions.",
    category: "Cross-Platform",
    projectType: "Personal Project",
    technologies: ["Next.js", "TailwindCSS", "React lucide"],
    githubUrl: "https://github.com/sabasiddique1/nft-detail-screen.git",
    demoUrl: "https://nft-detail-screen.vercel.app/",
    slug: generateSlug("NFT Detail Page – Web3 UI"),
    color: "#B026FF",
    image: "/nft.png",
    images: [
      "/nft.png",
      "/nft2.png",
    ],
  },
  {
    id: 8,
    title: "Pokedex - Pokemon App",
    description: "A fun and interactive Pokedex app that allows users to explore and search through a collection of Pokemon. Integrated with Pokemon API for comprehensive data and detailed information pages.",
    category: "Web App",
    projectType: "Personal Project",
    technologies: ["Node.js", "React", "CSS"],
    githubUrl: "https://github.com/sabasiddique1/Pokedex_App.git",
    demoUrl: "https://pokedex-app-sigma-silk.vercel.app/pokemon",
    slug: generateSlug("Pokedex - Pokemon App"),
    color: "#B026FF",
    image: "/pokemon.png",
    images: [
      "/pokemon.png",
      "/pokemon2.png",
    ],
    featured: true,
  },
  {
    id: 9,
    title: "Miniature App",
    description: "A collection of small, functional web apps built with JavaScript to demonstrate core logic and UI concepts. Each app is self-contained and showcases specific programming patterns in a lightweight format.",
    category: "Web App",
    projectType: "Personal Project",
    technologies: ["JavaScript", "HTML", "CSS"],
    githubUrl: "https://github.com/sabasiddique1/miniatureapps.git",
    demoUrl: "https://miniatureapps.vercel.app/",
    slug: generateSlug("Miniature App"),
    color: "#00F5FF",
    image: "/mini.png",
    images: [
      "/mini.png",
      "/mini2.png",
    ],
  },
  {
    id: 11,
    title: "VPC+",
    description: "Cloud-based SaaS for end-to-end multi-cloud migrations, disaster recovery, cost optimization, and compliance tracking. Fixed critical bugs and improved overall platform stability and performance.",
    category: "Web App",
    projectType: "Company Project",
    technologies: ["React.js", "Node.js", "PostgreSQL", "TailwindCSS"],
    demoUrl: "https://www.wanclouds.net/vpc+",
    slug: generateSlug("VPC+"),
    color: "#00F5FF",
    image: "/vpc+.png",
  },
  {
    id: 13,
    title: "EasyLlama",
    description: "Compliance training platform that is fully compliant with state laws and accessible 24/7 on PC and phone. Features real-life scenarios, quizzes, high-quality videos, and seamless HR tool integration.",
    category: "Company Project",
    projectType: "Company Project",
    technologies: ["Next.js", "TailwindCSS", "ShadCN"],
    demoUrl: "https://www.easyllama.com/",
    slug: generateSlug("EasyLlama"),
    color: "#00F5FF",
    image: "/easyllama.png",
  },
  {
    id: 14,
    title: "SendScale",
    description: "Break through Gmail's daily limits with SendScale's automated email warm-up and smart campaign builder. Features unified inbox for cold email outreach that actually works with comprehensive monitoring and error tracking.",
    category: "Company Project",
    projectType: "Company Project",
    technologies: ["Next.js", "NestJS", "Ant Design", "TailwindCSS", "Sentry"],
    demoUrl: "https://sendscale.ai/",
    slug: generateSlug("SendScale"),
    color: "#B026FF",
    image: "/sendscale.png",
  },
  {
    id: 17,
    title: "Smodin",
    description: "Uncover AI-written text and transform it into undetectable, human-like writing. Detect and bypass AI confidently with Smodin's intelligent tools and advanced content analysis capabilities.",
    category: "Web App",
    projectType: "Company Project",
    technologies: ["React.js", "Next.js", "TailwindCSS", "AI Integration"],
    demoUrl: "https://smodin.io/",
    slug: generateSlug("Smodin"),
    color: "#00F5FF",
    image: "/smodin.png",
  },
  {
    id: 18,
    title: "Rewritely",
    description: "Undetectable AI Writer and Humanizer platform for content transformation. Features advanced natural language processing with multiple rewriting modes and quality controls.",
    category: "Web App",
    projectType: "Company Project",
    technologies: ["React.js", "Next.js", "TailwindCSS", "AI Integration"],
    demoUrl: "https://rewritely.io/",
    slug: generateSlug("Rewritely"),
    color: "#B026FF",
    image: "/rewritely.png",
  },
  {
    id: 20,
    title: "URFX",
    description: "Join URFX—the best prop trading firm offering instant-funded forex and futures-style trading with no challenge. Features fair profit splits and AI-driven risk management tools for seamless trading experience.",
    category: "Web App",
    projectType: "Company Project",
    technologies: ["React.js", "Next.js", "TailwindCSS", "Trading APIs", "AI Integration"],
    demoUrl: "https://urfx.io/",
    slug: generateSlug("URFX"),
    color: "#B026FF",
    image: "/urfx.png",
  },
  {
    id: 21,
    title: "FXEE",
    description: "Fxee.ai is your AI-powered trading assistant that provides intelligent insights and market analysis. Features automated trading recommendations and real-time data processing for forex traders.",
    category: "Web App",
    projectType: "Company Project",
    technologies: ["React.js", "Next.js", "TailwindCSS", "AI Integration", "Trading APIs"],
    demoUrl: "https://fxee.ai/signin",
    slug: generateSlug("FXEE"),
    color: "#00F5FF",
    image: "/fxee.png",
  },
  {
    id: 23,
    title: "Propafund Dashboard",
    description: "Propafund is your trusted investment platform for portfolio management and investment tracking. Features real-time portfolio tracking, performance analytics, and secure authentication for investors.",
    category: "Web App",
    projectType: "Company Project",
    technologies: ["React.js", "Next.js", "TailwindCSS", "Investment Platform"],
    demoUrl: "https://propafund-dashboard.vercel.app/home",
    slug: generateSlug("Propafund Dashboard"),
    color: "#00F5FF",
    image: "/propafund.png",
  },
  {
    id: 24,
    title: "FX Utopia",
    description: "Professional trading dashboard for FX Utopia with advanced charting and real-time market data. Features comprehensive trading tools, order management systems, and high-performance data processing.",
    category: "Web App",
    projectType: "Company Project",
    technologies: ["React.js", "Next.js", "TailwindCSS", "Trading Platform"],
    demoUrl: "https://fxutopia.com/",
    slug: generateSlug("FX Utopia"),
    color: "#B026FF",
    image: "/utopia.png",
  },
]

